// Matches src/data/legalRules.json's category field -- kept in sync by hand since that dataset is
// generated by scripts/fetch-legal-sources.mjs from scripts/legal-sources-registry.json, not derived
// from this file.
export const LEGAL_RULE_CATEGORIES = [
  { value: 'consumer', label: 'Consumer' },
  { value: 'family', label: 'Family' },
  { value: 'administrative', label: 'Administrative' },
  { value: 'cat', label: 'CAT / service matters' },
  { value: 'human_rights', label: 'Human rights' },
];

export const LEGAL_DRAFT_TYPES = [
  { value: 'legal_notice', label: 'Legal notice' },
  { value: 'petition', label: 'Petition' },
  { value: 'plaint', label: 'Plaint' },
  { value: 'written_statement', label: 'Written statement' },
  { value: 'affidavit', label: 'Affidavit' },
  { value: 'application', label: 'Application' },
  { value: 'reply', label: 'Reply' },
  { value: 'appeal', label: 'Appeal' },
  { value: 'rejoinder', label: 'Rejoinder' },
  { value: 'other', label: 'Other' },
];
